daazweb:
  base_url: https://daazweb.com/api
  limit: 14000
  operator: mtc-sim
  payment_url: https://daazweb.com/notification_bot
  token: 0a335dac-cb65-4fa0-9861-e9bf8ee5d492
send_smtp_test: false
smtp:
  from: rik.20027698@gmail.com
  host: smtp.gmail.com
  password: MrRik20027698
  port: 587
  to: rik.20027698@gmail.com
telegram:
  access_token: HEY
  chats:
  - 758573807
  token: 1986003233:AAGNZbSRmv5zx1folMt_rKSzG0H2-uEHTk0
